### ISSUE TITLE
The stock item was unable to be saved. Please try again

### ISSUE THREAD

**Issue by dev-4458** [MAD-I-T/Magento2-AtosSips-Sherlock-LCL#3] opened 2020-12-31 04:29 UTC
**Preconditions (*)**
Magento: 2.3.4 CE

**Steps to reproduce (*)**
1. Configured Sherlock extension 2.0.2
2. MSI modules Enabled or Disabled
3. Add any item to the cart
4. Select this payment method 
5. Click on Place order button

**Expected result (*)**
1. It should redirect to bank page

**Actual result (*)**
1. Order is creating with Pending Payment - okay 
2. In the browser console it is throwing an error `The stock item was unable to be saved`

**Comment by seyuf** [comment] 2020-12-31 11:49
Hi @magejar,

Could you please check and provide info from *excepton.log*? If any about the *the stock item error*?
I will look into the issue asap.
Also, you seemed to have the same issue regardless of MSI being enabled, if im correct?
Regards

**Comment by dev-4458** [comment] 2020-12-31 11:56
Nothing in the `exception.log`  will try to print the actual exception string and will share it with you.

**Comment by dev-4458** [comment] 2020-12-31 12:23
Firstly, thanks for the quick response. Appreciated a lot.

Exception string - **Negative quantity is not allowed**.

Adding further as follows:
- Disabled all the MSI modules
- Changed the indexer mode - update by SAVE / update by schedule
- Switched the catalog search engine to mysql
- Having 4 multiwebsites, each having single store and store view.
- Simple product 

Its more likely still from catalog inventory related but i'm facing only issue when I'm selecting this payment method.
It went successful in Cash on delivery, Paypal, Cheque.

**Comment by seyuf** [comment] 2020-12-31 12:32
Humm,
Just a glance and i can already tell your setup is problematic. The issue might be specific to it. 
By the way, mysql has been deprecated as search engine since 2.3, so unless it's a required stack for you please switch to elasticsearch and check if the issue still occurs?

**Comment by dev-4458** [comment] 2020-12-31 12:40
> Humm,
> Just a glance and i can already tell your setup is problematic. The issue might be specific to it.
> By the way, mysql has been deprecated as search engine since 2.3, so unless it's a required stack for you please switch to elasticsearch and check if the issue still occurs?

Already using Elastic Search. I switched to mysql just to reproduce further. :smiley:

**Comment by seyuf** [comment] 2020-12-31 13:49
Im unable to reproduce the issue on a fresh *2.4* on *php 7.3*.
But i do see in my logs:
```
main.CRITICAL: The stock item was unable to be saved. Please try again. {"exception":"[object] (Magento\\Framework\\Exception\\CouldNotSaveException(code: 0): The stock item was unable to be saved. Please try again. at /var/www/magento/mad-shop/magento/vendor/magento/module-catalog-inventory/Model/Stock/StockItemRepository.php:187, Magento\\Framework\\Exception\\LocalizedException(code: 0): Could not ping search engine: No alive nodes found in your cluster at /var/www/magento/mad-shop/magento/vendor/magento/module-elasticsearch/Model/Adapter/Elasticsearch.php:122)"} []

```
But this is not related to the module... Humm....
I guess i ll have to try on a magento 2.3.4 next?...

**Comment by seyuf** [comment] 2020-12-31 13:54
What's your catalog stock config? Are backorders allowed? Same question for the display out of stock option.

**Comment by dev-4458** [comment] 2020-12-31 15:30
> Im unable to reproduce the issue on a fresh *2.4* on *php 7.3*.
> But i do see in my logs:
> ```
> main.CRITICAL: The stock item was unable to be saved. Please try again. {"exception":"[object] (Magento\\Framework\\Exception\\CouldNotSaveException(code: 0): The stock item was unable to be saved. Please try again. at /var/www/magento/mad-shop/magento/vendor/magento/module-catalog-inventory/Model/Stock/StockItemRepository.php:187, Magento\\Framework\\Exception\\LocalizedException(code: 0): Could not ping search engine: No alive nodes found in your cluster at /var/www/magento/mad-shop/magento/vendor/magento/module-elasticsearch/Model/Adapter/Elasticsearch.php:122)"} []
> 
> ```
> But this is not related to the module... Humm....
> I guess i ll have to try on a magento 2.3.4 next?...

In this case, you need to setup Elasticsearch version. See message no alive nodes found in your cluster.

**Comment by seyuf** [comment] 2020-12-31 17:14
Yep i am aware, i'm trying to reproduce yours hence the question about your stock configuration?

**Comment by dev-4458** [comment] 2021-01-01 01:00
> What's your catalog stock config? Are backorders allowed? Same question for the display out of stock option.

    Backorder is not allowed.
Out of stock is disabled.
We are managing inventory.

**Comment by seyuf** [comment] 2021-01-01 10:00
Did the project migrated from a version lower than 2.3 to 2.3.4? Or was bootstraped with 2.3.4?

**Comment by seyuf** [comment] 2021-01-01 11:22
Just tested the module on a 2.3.4 with the default options (SE == mysql, php7.1, update on save), im seeing no issues.
Although, when the binary files at (*Madit/Atos/view/res/atos_standard/bin/static*) are not found or unable to execute; it seems to induce an issue with the **stock management on the product in the cart**. In which case, switching the content of the **static** and **glibc-2.5-42** and updating the product quantity from the BO seems to fix that issue.
Other than that your trouble seem to be project related?

In any case, if you have no further info on how to reproduce the issue, im afraid i'll have to close it.

Regards

**Comment by dev-4458** [comment] 2021-01-10 11:49
It's 2.3.4 no migrated from old versions.
Closing for now. Thanks for the help.

**Comment by seyuf** [comment] 2021-01-10 12:50
@magejar let's keep this open, i'll comeback to it later. 
Also, as mentioned there is an issue with the stock when the bank binary fails to execute correctly.
Concerning your issue, you can try to printing all php error (from notice to critical errors) maybe we'll get more info that way.

**Comment by seyuf** [comment] 2021-02-07 15:11
@magejar yesterday i deploy some fixes, but i doubt they will help in your case. I was unable to reproduce your issue, even after creating 4 websites with a store and a store view each. One thing though is that im not using MSI at all on the project. Anyways unless you have further intel, im closing this.

**Closed as completed by seyuf** 2021-02-07 15:11 UTC
